### ISSUE TITLE
Freezes and skipping frames 

### ISSUE THREAD

**Issue by Hula1267** [dtankdempse/daddylive-m3u#10]
I get a lot fo freezes and skipping frames over Tivimate Playlist. 

60 mbits network in Canada
Dont have problem streaming anything
DDlive website sometime freeze but rarely. Really not that much!

Is there a way to lower that or no getting at all.

**Comment by dtankdempse** [comment]
Unfortunately, there's not much that can be done about the freezing. Sometimes the stream works better than other times. You can try clearing your cache to see if that helps improve stability.
