### ISSUE TITLE
EPG is not working

### ISSUE THREAD

**Issue by Jag4343** [dtankdempse/daddylive-m3u#11]
EPG for daddy live-M3U is not working

**Comment by dtankdempse** [comment]
M3u4u, the service provider for most of the EPGs, is currently down. Once they are back up, the guide data will start working again. More information is available on their Discord: https://m3u4u.com/discord.

**Comment by Jag4343** [comment]
Thank you for the update. I appreciate all of your playlists and look forward to more of them.
