### ISSUE TITLE
Channels stop working

### ISSUE THREAD

**Issue by joaquinito2070** [dtankdempse/daddylive-m3u#13]
Please fix it.

**Comment by dtankdempse** [comment]
I couldn't identify any issues on my end. Could you please provide more details about the problem you're experiencing? It would also help to know which playlist you're using and any relevant information about your setup.

**Comment by dtankdempse** [comment]
The only issue I found was with the VLC playlist, but I've fixed it, and it should be working now. If you're experiencing a different problem, please let me know.

**Comment by zrrs** [comment]
Hi!

I'm using a raspi 5 with libreelec 12.0.1 (Kodi Omega 21.1). 
The channels are loaded correctly and the EPG too but when I try to see a channel Kodi says that there is no source (or something like that).

If you want the exact message I will post this evening.

Thanks for your work.

**Comment by zrrs** [comment]
Hi! I tried yesterday and all was working.

Thank you very much!
