### ISSUE TITLE
Standard Playlist Information User-Agent incorrect or no longer working

### ISSUE THREAD

**Issue by JHarding86** [dtankdempse/daddylive-m3u#22]
I just tried getting these streams working for the past couple hours with threadfin. The only thing that made them work was changing the User-Agent to what is posted inside of the VLC or Kodi lists.

**Comment by Tw1zT3d2four7** [comment]
if you want to use the standard version but don't want to use a m3u proxy. you can use this ffmpeg profile in streammaster or threadfin to watch them. 

-hide_banner -loglevel error -user_agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" -referer "https://ilovetoplay.xyz/" -headers "Origin: https://ilovetoplay.xyz" -abort_on empty_output -re -thread_queue_size 1024 -rtbufsize 0.5MB -fix_sub_duration -analyzeduration 3500000 -probesize 4000000 -ignore_unknown -i {streamUrl} -ignore_unknown -fflags -reconnect 1 -map 0:v -map 0:a? -map 0:s? +genpts+discardcorrupt -preset ultrafast -tune zerolatency -timeout 6000000 -muxdelay 0.001 -max_interleave_delta 0 -report -copyts -c copy -report -f mpegts pipe:1

**Comment by JHarding86** [comment]
Yea, that user agent string doesn't work

**Comment by dtankdempse** [comment]
> Yea, that user agent string doesn't work

I just checked, and it seems to be working fine for me.

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`

**Comment by JHarding86** [comment]
Thats strange I get 403 errors when using that User-Agent.

A different question, how can I get an epg.xml file that works with all_channels playlist? https://github.com/dtankdempse/daddylive-m3u/blob/main/all_channels/playlist.m3u8

**Comment by dtankdempse** [comment]
> Thats strange I get 403 errors when using that User-Agent.
> 
> A different question, how can I get an epg.xml file that works with all_channels playlist? https://github.com/dtankdempse/daddylive-m3u/blob/main/all_channels/playlist.m3u8

There are multiple sources where you can try to find EPG data:

https://epg.pw/
https://epgshare01.online/epgshare01/
https://m3u4u.com/

However, I haven't been able to find an all in one source for all the DaddyLive channels. I will continue mapping them as I have more time. If you find any other sources, please share them, and I can map those channels.

**Comment by JHarding86** [comment]
Very cool thank you for the help! If I find more sources, Ill let you know.
