### ISSUE TITLE
Add Altitude Sports from daddylive

### ISSUE THREAD

**Issue by JHarding86** [dtankdempse/daddylive-m3u#23]
Can you add the Altitude Sports Daddylive channel from Daddylive? Or give an example of how to extract the m3u8 file from Daddylive for me so I can extract channels on my own?

Edit: clarity

**Comment by dtankdempse** [comment]
The channel has been added to the playlist. EPG data will appear after the epg-grabber completes its next scheduled run.

**Comment by JHarding86** [comment]
Thank you for the info! What is your logic for the channels you have added?
