### ISSUE TITLE
request: daily events playlist 

### ISSUE THREAD

**Issue by kr341** [dtankdempse/daddylive-m3u#24]
Great work
Can you add the daily events as a playlist?

**Comment by dtankdempse** [comment]
Yes, I’ll add this as soon as I get time. DaddyLive already provides the Schedule API, which makes it fairly easy to do.

**Comment by dtankdempse** [comment]
This has now been added.

**Comment by bradenglund** [comment]
Is it possible to adjust the update interval or update time for the events? I've notice that at ~6pm eastern, there is a lag between events listed and those currently streaming on the site.

**Comment by dtankdempse** [comment]
> Is it possible to adjust the update interval or update time for the events? I've notice that at ~6pm eastern, there is a lag between events listed and those currently streaming on the site.

Yes, I’ll monitor their API today to pinpoint the exact time they update their data, as they currently don’t provide any detailed information about their update schedule.

**Comment by dtankdempse** [comment]
The updated events are available around 10:00 PM GMT. The script will automatically check for updates and add those new events into the playlist.
