### ISSUE TITLE
XML epg is no longer loading

### ISSUE THREAD

**Issue by infojoe** [dtankdempse/daddylive-m3u#27]
Epg is set to "testing" branch and not loading. Also can there be a duplicate playlist pointing to the gzipped version of epg?

**Comment by emaschi5** [comment]
working for me

**Comment by infojoe** [comment]
If you think it's working, please try clearing your cache and/or data and
try to reload the epg fresh. The only way I got it to work was manually
saving the playlist locally and editing to remove the "testing" subfolder
in url.

**Comment by emaschi5** [comment]
i delete the playlist, delete the app and reinstalled, the EPG are working, i'm using this https://bit.ly/ddy-epg1

**Comment by dtankdempse** [comment]
> Epg is set to "testing" branch and not loading. Also can there be a duplicate playlist pointing to the gzipped version of epg?

I’ve fixed this. Thanks for the heads up! As for the GZ version, creating an entirely new playlist just to embed the GZ file seems excessive. Are you unable to load the compressed version directly by URL in your application?

**Comment by infojoe** [comment]
I think maybe I was getting rate limited. I was trying a few different
players. I prefer "Sparkle TV" over Tivimate, but Sparkle doesn't let you
edit the epg url unless you buy the "Plus" version..

**Comment by infojoe** [comment]
Seems all good now. Thanks.
