### ISSUE TITLE
Is this Script Related?

### ISSUE THREAD

**Issue by Spainguy77** [dtankdempse/daddylive-m3u#30]
Noticed a strange phenomenon on Daddylive streams: ALL channels, regardless of resolution or frame rate, stream at 4mbps. Is this from source or is it script enforced?

**Comment by dtankdempse** [comment]
The playlist is directly sourced from Daddylive servers without any modifications. It includes only a single streaming option in their playlist.

**Comment by Spainguy77** [comment]
> The playlist is directly sourced from Daddylive servers without any modifications. It includes only a single streaming option in their playlist.

Ok, appreciate the clarification

**Comment by dtankdempse** [comment]
> > The playlist is directly sourced from Daddylive servers without any modifications. It includes only a single streaming option in their playlist.
> 
> Ok, appreciate the clarification

I am working on adding a playlist that has SD streams. https://github.com/dtankdempse/topembed-m3u/ Still testing and setting it up though.
