### ISSUE TITLE
Xml EPG on TIVIMATE not working

### ISSUE THREAD

**Issue by emaschi5** [dtankdempse/daddylive-m3u#36]
Hi, unfortunately from yesterday the EPG are not working

**Comment by dtankdempse** [comment]
It should be working now.

**Comment by emaschi5** [comment]
Hi, wonderful job the events work well, but with tivimate free I need to delete and insert again the playlist. It s not updating with the free version

could you please update the playlist also for implayer? I tried the tivimate but is not working
