### ISSUE TITLE
BT Sport >> TNT Sports

### ISSUE THREAD

**Issue by bradenglund** [dtankdempse/daddylive-m3u#37]
TNT Sports channels are mislabeled as BT Sport (former name). I suspect this is also breaking the EPG for these channels

`
#EXTINF:-1 tvg-id="TNT.Sports.1.uk" tvg-name="BT Sport 1" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bt-sport-1-uk.png" group-title="SPORTS (DADDY LIVE)" ,BT Sport 1
https://xyzdddd.mizhls.ru/lb/premium31/index.m3u8|Referer=https://cookiewebplay.xyz/|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/132.0|Origin=https://cookiewebplay.xyz
#EXTINF:-1 tvg-id="TNT.Sports.2.uk" tvg-name="BT Sport 2" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bt-sport-2-uk.png" group-title="SPORTS (DADDY LIVE)" ,BT Sport 2
https://xyzdddd.mizhls.ru/lb/premium32/index.m3u8|Referer=https://cookiewebplay.xyz/|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/132.0|Origin=https://cookiewebplay.xyz
#EXTINF:-1 tvg-id="TNT.Sports.3.uk" tvg-name="BT Sport 3" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bt-sport-3-uk.png" group-title="SPORTS (DADDY LIVE)" ,BT Sport 3
https://xyzdddd.mizhls.ru/lb/premium33/index.m3u8|Referer=https://cookiewebplay.xyz/|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/132.0|Origin=https://cookiewebplay.xyz
#EXTINF:-1 tvg-id="TNT.Sports.4.uk" tvg-name="BT Sport 4" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bt-sport-4-uk.png" group-title="SPORTS (DADDY LIVE)" ,BT Sport 4`

**Comment by dtankdempse** [comment]
This has been fixed.
