### ISSUE TITLE
Version For implayer app

### ISSUE THREAD

**Issue by emaschi5** [dtankdempse/daddylive-m3u#39]
Hi, wonderful job the events work well, but with tivimate free I need to delete and insert again the playlist. It s not updating with the free version

could you please update the playlist also for implayer? I tried the tivimate but is not working

**Comment by dtankdempse** [comment]
iMPlayer doesn't support passing headers, only a global User-Agent setting. If you'd like, message me on Discord (dtanks_86578), and I can help you with an app.

**Comment by emaschi5** [comment]
added, let me know when you are available, i only need an app with updating playlists. thanks a lot
