### ISSUE TITLE
Playlist not working

### ISSUE THREAD

**Issue by BuddyChewChew** [dtankdempse/daddylive-m3u#4]
Tried all 3 urls and the raw playlist file. Cant get to work on Tivimate or vlc.

**Comment by dtankdempse** [comment]
I'm aware of it. They keep making changes and i'm looking into it.

**Comment by BuddyChewChew** [comment]
ok, good stuff

**Comment by element465** [comment]
Thanks, I just discovered this yesterday and thought I had been IP blocked

**Comment by whitesnakeftw** [comment]
Works with a regular desktop Chrome user-agent, example:

```
#EXTINF:-1, NBCSBA
https://xyzdddd.mizhls.ru/lb/premium753/index.m3u8|Referer=https://ilovetoplay.xyz/|Origin=https://ilovetoplay.xyz|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
```

**Comment by stein-dev** [comment]
It's working now!

**Comment by BuddyChewChew** [comment]
Thank you.

**Comment by stein-dev** [comment]
Using only the referrer tag is also working without setting the user-agent and origin. Tried it using mpv.
mpv --http-header-fields='Referer: https://ilovetoplay.xyz/' https://xyzdddd.mizhls.ru/lb/premium51/index.m3u8

**Comment by BuddyChewChew** [comment]
I just changed the User-Agent setting in TiviMate for the playlist to.

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by Phunky** [comment]
No look for me :/ i'm running this on emby via the cloudfront proxy. Was working OK yesterday morning but then everything started to buffer.

Noticed on their telegram chat something about sorting out security 🤷‍♂️

**Comment by Phunky** [comment]
I’ll give that a bash later then 💪

**Comment by Kevsosmooth** [comment]
Just started messing around with the cloudflare version and got to the point where I enter url, header, agent all that good stuff and added it to my vlc but its just skipping every channel and never stopping to play one.

Which version are people currently using it for this to work?
