### ISSUE TITLE
Source EPG's Changed the name of many channels.

### ISSUE THREAD

**Issue by JHarding86** [dtankdempse/daddylive-m3u#41]
The sources that are being used for generating the custom epg.xml has changed the name of many of their channels. This causes the EPG's to contain no information for channels who's names have changed that are in the playlists and corresponding tvg-ids.txt

**Comment by dtankdempse** [comment]
I have been working on remapping them. Thanks.

**Comment by JHarding86** [comment]
I'm not sure what you are using to map the Daddylive channels to EPG data, but in my fork of your repo I have created a tool in an attempt to make this easier. The code is honed for updating specific channels, but it can be easily modified. This is how I updated my EPGs the other day when EPGShare changed all of their channel IDs.

https://github.com/JHarding86/daddylive-m3u/blob/main/Daddylive%20scraper.py
