### ISSUE TITLE
Dynamic M3U data incompatible with Plex

### ISSUE THREAD

**Issue by JHarding86** [dtankdempse/daddylive-m3u#46]
It seems that because the schedule API data is changing daily it is running interference with Plex.

It kinda seems like Plex does not update the M3U file once it has imported it, so even if Stream Master or Threadfin update it, plex does not. This means that the M3U links aren't valid after a day passes from the initial import into plex. 

Do you have any ideas about what is going on here or a solution?

**Comment by dtankdempse** [comment]
I don't use Plex so I had to ask AI:

Here’s a simple .bat file you can use to trigger a Plex library refresh via the Plex API. You can schedule it using the Windows Task Scheduler to run at regular intervals.
Steps to Create the .bat File

  Download and extract the .zip file.
 
[plex_refresh.zip](https://github.com/user-attachments/files/17986705/plex_refresh.zip)

How to Set Up with Windows Task Scheduler

    Open Task Scheduler:
        Press Win + S, type "Task Scheduler," and press Enter.

    Create a New Task:
        Click on Create Task... in the right-hand menu.

    Set General Settings:
        Give your task a name, e.g., "Plex Library Refresh."
        Select "Run whether user is logged on or not" if you want it to run in the background.
        Check "Run with highest privileges."

    Set a Trigger:
        Go to the "Triggers" tab.
        Click New... and choose how often you want to run the task (e.g., daily, weekly, or every few hours).
        Set the start time and recurrence interval.

    Set the Action:
        Go to the "Actions" tab.
        Click New... and choose "Start a Program."
        Browse to the .bat file you just created.

    Save the Task:
        Click OK to save the task.
        Enter your Windows username and password if prompted.

Notes (open the .bat file and edit the details.)

    Replace 192.168.1.100 with your Plex server's IP address.
    Obtain your Plex token by following Plex's guide.
    Replace 1 with your library ID. You can find this by inspecting the API endpoints in a browser or API tool.

Now, the .bat file will automatically run at the intervals you’ve configured in the Task Scheduler, refreshing your Plex library programmatically!

**Comment by dtankdempse** [comment]
The first message I sent was wrong. Download, extract and edit this .bat file in a text editor.

[plex_refresh-playlist.zip](https://github.com/user-attachments/files/17986759/plex_refresh-playlist.zip)

Steps to Set Up Windows Task Scheduler

    Create the Script:
        Copy the script above into a .bat file, e.g., plex_reimport.bat.
        Replace the placeholders (PLEX_SERVER_IP, PLEX_TOKEN, LIBRARY_ID, and M3U_URL) with your Plex server details.

    Open Task Scheduler:
        Press Win + S, search for "Task Scheduler," and open it.

    Create a New Task:
        Click Create Task... in the right panel.

    Configure the General Tab:
        Give your task a name, e.g., "Plex Playlist Reimport."
        Select "Run whether user is logged on or not."
        Check "Run with highest privileges."

    Set a Trigger:
        Go to the "Triggers" tab and click New....
        Choose when you want the task to run (e.g., daily, at startup, or when triggered manually).
        Set the desired schedule and save.

    Set the Action:
        Go to the "Actions" tab and click New....
        Choose "Start a Program."
        Browse to your plex_reimport.bat file.

    Save the Task:
        Click OK and enter your Windows user credentials if prompted.

What This Script Does

    Deletes the Existing Playlist Source: It uses the Plex API to remove the current M3U source from the library.
    Re-Adds the Playlist Source: It re-adds the M3U URL as a new source to ensure Plex re-imports the updated playlist.
    Logs the Activity: It creates a log file (plex_reimport_log.txt) to confirm when the task was run.

**Comment by JHarding86** [comment]
Can you please just paste the contents of the script in a comment?

**Comment by dtankdempse** [comment]
@echo off
:: Replace the following placeholders with your Plex details
set "PLEX_SERVER_IP=192.168.1.100"    :: Replace with your Plex server IP
set "PLEX_TOKEN=YOUR_PLEX_TOKEN"      :: Replace with your Plex token
set "LIBRARY_ID=1"                    :: Replace with your library ID (find it in Plex API)
set "M3U_URL=http://yourserver.com/playlist.m3u"  :: Replace with your M3U file URL

:: Step 1: Delete the existing playlist source
echo Deleting existing M3U source...
curl -X DELETE "http://%PLEX_SERVER_IP%:32400/library/sections/%LIBRARY_ID%?X-Plex-Token=%PLEX_TOKEN%"

:: Step 2: Re-add the M3U source
echo Re-adding M3U source...
curl -X POST -H "Content-Type: application/json" -d "{\"url\": \"%M3U_URL%\"}" ^
"http://%PLEX_SERVER_IP%:32400/library/sections?X-Plex-Token=%PLEX_TOKEN%"

:: Log the re-import action
echo Re-import triggered at %date% %time% >> "%~dp0plex_reimport_log.txt"
echo Done!

**Comment by dtankdempse** [comment]
I'm not sure about this. Looking over the script, I noticed a potential issue: the ID seems to change dynamically

You can try this one:

@echo off
:: Replace with your Plex details
set "PLEX_SERVER_IP=192.168.1.100"    :: Replace with your Plex server IP
set "PLEX_TOKEN=YOUR_PLEX_TOKEN"      :: Replace with your Plex token

:: Log the refresh attempt
echo Refreshing all libraries at %date% %time% >> "%~dp0plex_refresh_log.txt"

:: Trigger a refresh for all libraries
curl -X GET "http://%PLEX_SERVER_IP%:32400/library/sections/all/refresh?X-Plex-Token=%PLEX_TOKEN%"

:: Confirm completion
echo All libraries refreshed. >> "%~dp0plex_refresh_log.txt"

**Comment by JHarding86** [comment]
The DVR in plex isn't considered a library. 

Your thoughts have inspired me, I'll post a script here when I'm all done. 

Thank you for the ideas.

**Comment by JHarding86** [comment]
I think I have solved the issue in my fork. As opposed to reloading the Tuner into Plex every day, I have tried to make a more proper solution. Essentially, each channel must have M3U8 and the EPG data when initially loaded into plex. Then Plex knows that the channel exists and that it has valid EPG data that could / should be updated.
