### ISSUE TITLE
No EPG for Australian Fox sports channels

### ISSUE THREAD

**Issue by sd26** [dtankdempse/daddylive-m3u#5]
Hi

I have Tivi mate and set up using the URLs provided. Australian Fox Sports 502 thru 507 have no EPG information.

Nearly all other channels EPG information is provided is it possible to add EPG for these Australian Fox sports channels.

Thanks for you work.

**Comment by dtankdempse** [comment]
The issue is that m3u4u has, for some reason, removed all the Australian channels from their service. I'll look around for an alternative source and see what I can come up with.

**Comment by dtankdempse** [comment]
This should now be fixed.
