### ISSUE TITLE
Can tv logos be added.

### ISSUE THREAD

**Issue by inc16sec** [dtankdempse/daddylive-m3u#51]
So far there are only few channels that have logos on them, while others have the daddy logo as the default logo. I'm thinking if logos can be added instead of the default one. I'm willing to help if possible and we can extract the logos from [](https://github.com/tv-logo/tv-logos.)

**Comment by dtankdempse** [comment]
Yeah, I plan to go back through the playlist and add the logos. Once I finish the M3U Mapper I’ve been working on, it’ll be much easier for me to add them. Its taking a bit longer than I expected to complete, but hopefully, I’ll have it done sometime next week.

**Comment by inc16sec** [comment]
Glad to hear that. Thanks for the response.
