### ISSUE TITLE
Bally Sports Channels not showing up in full or English playlist 

### ISSUE THREAD

**Issue by tmess11** [dtankdempse/daddylive-m3u#58]
Is there a way to add the suite of Bally Sports channels (American regional sports networks) into the English playlist? 

They are all available on the DaddyLive Website but not under the 24/7 networks tab. Not sure if that will be an issue.

Bally Sports Arizona stream/stream-890.php
Bally Sports Detroit stream/stream-891.php
Bally Sports Florida stream/stream-892.php
Bally Sports Great Lakes stream/stream-893.php
Bally Sports Indiana stream/stream-894.php
Bally Sports Kansas City stream/stream-895.php
Bally Sports Midwest stream/stream-896.php
Bally Sports New Orleans stream/stream-897.php
Bally Sports North stream/stream-898.php
Bally Sports Ohio stream/stream-899.php
Bally Sports Oklahoma stream/stream-900.php
Bally Sports San Diego stream/stream-901.php
Bally Sports SoCal stream/stream-902.php
Bally Sports South stream/stream-903.php
Bally Sports Southeast stream/stream-904.php
Bally Sports Sun stream/stream-905.php
Bally Sports West stream/stream-906.php
Bally Sports Wisconsin stream/stream-907.php

**Comment by dtankdempse** [comment]
This has been added.

**Comment by tmess11** [comment]
Thank you!
