### ISSUE TITLE
EPG format for Plex

### ISSUE THREAD

**Issue by philipbutts** [dtankdempse/daddylive-m3u#6]
The EPG provided, when used in plex, displays all programs as "new", and is not relaying the proper episode metadata, resulting in things like recordings being marked as "Episode: Current date". I've learned a bit about why this is happening, and even found a format converter, but I've had no success making it work. Is there a chance of getting a second EPG format, or a simple conversion program? Besides that, I've had a great deal of success implementing this in plex, thank you for your hard work.

**Comment by dtankdempse** [comment]
The EPG source used for this playlist comes from m3u4u.com, and after looking into it, it seems they don't support the use of `<episode-num>`. To get episode numbers, you'll need to use another EPG service that supports these tags. You can give WebGrab+Plus a try.

## WebGrab+Plus
WebGrab+Plus allows you to scrape EPG data from various websites. Depending on the source, it can support `<episode-num>`. If the source website includes episode numbers, WebGrab+Plus can include them in the XMLTV output. [WebGrab+Plus website](http://webgrabplus.com/).

**Comment by philipbutts** [comment]
Thank you very much, I will look into it right away. I'll also keep an eye out for any fixes on your end.

**Comment by dtankdempse** [comment]
The new EPG should now include the data you were requesting.
