### ISSUE TITLE
Add Sports Channel(s)

### ISSUE THREAD

**Issue by tmess11** [dtankdempse/daddylive-m3u#60]
Can you add SportsNet Pittsburgh (regional Sports network) to the English Playlist?
Also, I see that there are the NFL Sunday Ticket channels in the epg on the DaddyLive website, but not on the channel list. I don't know if they could be added too?

Thanks!

**Comment by dtankdempse** [comment]
SportsNet Pittsburgh has been added. The Daddylive "Schedule API" is already included and can be found under the group "Events (DADDY LIVE)
