### ISSUE TITLE
On october 20th 2024, Daddy live VLC playlist is broken. Channels wont load anymore. Probably wrong referer?

### ISSUE THREAD

**Issue by Hula1267** [dtankdempse/daddylive-m3u#7]
Same issue with m3u-playlist-proxy using header privided in the readme page (https://github.com/dtankdempse/daddylive-m3u?tab=readme-ov-file)

Referer: https://lewblivehdplay.ru/
Origin: https://lewblivehdplay.ru
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by dtankdempse** [comment]
I've updated the header information and domain for playlist.m3u8. I didn't encounter any issues with the VLC playlist; it loaded and played correctly when I tested it.

**Comment by Hula1267** [comment]
Sorry! 

VLC
Resetted / Updated VLC to freshesh version. Now it works using https://raw.githubusercontent.com/dtankdempse/daddylive-m3u/refs/heads/main/vlc_playlist.m3u8

M3U-Playlist-Proxy
Tried m3u-playlist-proxy and it's not working with PotPlayer (same host) but VLC is ok. 

For what other player or use cases m3u-playlist-proxy is intended?

**Comment by dtankdempse** [comment]
How are you running the m3u-playlist-proxy? If you're using a Cloudflare Worker, it no longer works with DaddyLive. Their server returns a 403 response when it detects requests coming from a Worker. You would need to use one of the other options.

**Comment by Hula1267** [comment]
I'm on my localhost. 

Tried Potplayer on same host  = no loading at all
Tried Sparkle TV on another host : channel load, but stop after 5-10 sec. All of them. 

![image](https://github.com/user-attachments/assets/921e4807-9cde-4b60-abec-4762f3034727)

**Comment by dtankdempse** [comment]
You are still using the old header information.

As stated here in my reply, I have updated the header information. 
> I've updated the header information and domain for playlist.m3u8. I didn't encounter any issues with the VLC playlist; it loaded and played correctly when I tested it.

Try the new header information posted in the read me file.
