### ISSUE TITLE
DDlive VLC playlist / error at the end?

### ISSUE THREAD

**Issue by Hula1267** [dtankdempse/daddylive-m3u#9]
End of standard playlist. Error or intended? https://bit.ly/ddy-m3u4

<img width="899" alt="image" src="https://github.com/user-attachments/assets/4ada1b72-dc12-44e0-9001-2cbae67e4fae">

**Comment by dtankdempse** [comment]
This issue has been fixed. It would be helpful if you could keep all related discussions in the same issue you opened, rather than opening multiple issues.
